Fix initialization of Globals pointer
This is supposed to be the _end_ of globals, so needs to be moved initially.
Otherwise, we overwrite it, which causes messages like:

    catalog_error: Lookup malformed catalog (ns=5 vs=10 size=5)

when the globals catalog is overwritten by temporaries.

Signed-off-by: Christophe de Dinechin <christophe@dinechin.org>